<?php
/*
 * Copyright (c) 2020 SimpleWork
 * https://simple-work.nl ~ <info@simple-work.nl>
 * https://github.com/Julianvschijndel/SimpleWork
 * --------------------------------------------------
 * SimpleWork. ~ Version: 0.1
 * --------------------------------------------
 *
 * Please do not edit this file if you don't know what you are doing.
 * I will not give support if you edit this file and SimpleWork is not
 * working anymore. If you know what you're doing and then you think
 * you can or actually can improve my code then please make a pull request
 * and I will look into it.
 *
*/

// Error page 404.
$lang['404Title'] = "404 page not found.";
$lang['404H1'] = "Oops! Page Not Be Found";
$lang['404Text'] = "Sorry but the page you are looking for does not exist, have been removed. name changed or is temporarily unavailable";
$lang['404Button'] = "Go to the homepage.";

// Error page lang.
$lang['LangTitle'] = "Language file cannot be found.";
$lang['LangH1'] = "Oops! Language Not Be Found";
$lang['LangText'] = "Sorry but the language file <b>".APP_LANG."</b> does not exists.";
$lang['LangButton'] = "Go to the homepage.";

// Menu
$lang['aboutMePage'] = "About me";
$lang['contactMePage'] = "Contact me";

// Home
$lang['welcomeTitle'] = "Welcome to ".APP_NAME."!";
$lang['welcome'] = "Welcome to ".APP_NAME."!";
$lang['welcomeText'] = "Thank you for using <b>".APP_NAME."</b>!";

// About me
$lang['aboutTitle'] = "About me.";
$lang['aboutH1'] = "About me.";
$lang['aboutText'] = "Welcome to the about me page.";

// Contact me
$lang['contactTitle'] = "Contact me.";
$lang['contactH1'] = "Contact me.";
$lang['contactText'] = "Welcome to the contact me page.";


/*
 * Do not delete this!
*/
return $lang;
