<?php
/*
 * Copyright (c) 2020 SimpleWork
 * https://simple-work.nl ~ <info@simple-work.nl>
 * https://github.com/Julianvschijndel/SimpleWork
 * --------------------------------------------------
 * SimpleWork. ~ Version: 0.1
 * --------------------------------------------
 *
 * Please do not edit this file if you don't know what you are doing.
 * I will not give support if you edit this file and SimpleWork is not
 * working anymore. If you know what you're doing and then you think
 * you can or actually can improve my code then please make a pull request
 * and I will look into it.
 *
*/

// Error page 404.
$lang['404Title'] = "404 pagina niet gevonden.";
$lang['404H1'] = "Oeps! Pagina kon niet gevonden worden.";
$lang['404Text'] = "Sorry maar de pagina die je zoekt bestaat niet, is verwijderd. naam gewijzigd of is tijdelijk niet beschikbaar";
$lang['404Button'] = "Ga naar de homepagina.";

// Error page lang.
$lang['LangTitle'] = "Taal bestand kan niet gevonden worden.";
$lang['LangH1'] = "Oeps! Taal bestand bestaat niet.";
$lang['LangText'] = "Het spijt ons, maar het taalbestand <b>".APP_LANG."</b> bestaat niet.";
$lang['LangButton'] = "Ga naar de homepagina.";

// Menu
$lang['aboutMePage'] = "Over mij";
$lang['contactMePage'] = "Contacteer mij";

// Home
$lang['welcomeTitle'] = "Welkom op ".APP_NAME."!";
$lang['welcome'] = "Welkom op ".APP_NAME."!";
$lang['welcomeText'] = "Dankjewel voor het gebruiken van <b>".APP_NAME."</b>!";

// About me
$lang['aboutTitle'] = "Over mij";
$lang['aboutH1'] = "Over mij";
$lang['aboutText'] = "Welkom op de over mij pagina.";

// Contact me
$lang['contactTitle'] = "Contacteer mij";
$lang['contactH1'] = "Contacteer mij";
$lang['contactText'] = "Welkom op de contacteer mij pagina.";

/*
 * Do not delete this!
*/
return $lang;
