<?php
/*
 * Copyright (c) 2020 SimpleWork
 * https://simple-work.nl ~ <info@simple-work.nl>
 * https://github.com/Julianvschijndel/SimpleWork
 * --------------------------------------------------
 * SimpleWork. ~ Version: 0.1
 * --------------------------------------------
 *
 * Please do not edit this file if you don't know what you are doing.
 * I will not give support if you edit this file and SimpleWork is not
 * working anymore. If you know what you're doing and then you think
 * you can or actually can improve my code then please make a pull request
 * and I will look into it.
 *
*/

$lang[] = "";
$lang[] = "";
$lang[] = "";
$lang[] = "";
$lang[] = "";
$lang[] = "";
$lang[] = "";

/*
 * Do not delete this!
*/
return $lang;
