<?php
/*
 * Copyright (c) 2020 SimpleHtmlWork
 * https://github.com/Julianvschijndel/SimpleHtmlWork
 * --------------------------------------------------
 * SimpleHtmlWork. ~ Version: 1
 * --------------------------------------------
 *
 * Please do not edit this file if you don't know what you are doing.
 * I will not give support if you edit this file and SimpleHtmlWork is not
 * working anymore. If you know what you're doing and then you think
 * you can or actually can improve my code then please make a pull request
 * and I will look into it.
 *
*/

// Load in the router and set it with a function.
$router = new Router();

/*
 * Set all you're routes here. If you need to know how to set
 * a route then please check for more examples in the /docs/router.md
*/
$router->set('/', function (){
    Sw::View('index');
});

$router->set('/about', function (){
    Sw::View('about');
});

$router->set('/contact', function (){
    Sw::View('contact');
});


/*
 * Please do not change/delete this!
 * This function will create all te above routes!
*/
$router->createRoutes();
