<?php
/*
 * Copyright (c) 2020 SimpleHtmlWork
 * https://github.com/Julianvschijndel/SimpleHtmlWork
 * --------------------------------------------------
 * SimpleHtmlWork. ~ Version: 1
 * --------------------------------------------
 *
 * Please do not edit this file if you don't know what you are doing.
 * I will not give support if you edit this file and SimpleHtmlWork is not
 * working anymore. If you know what you're doing and then you think
 * you can or actually can improve my code then please make a pull request
 * and I will look into it.
 *
*/

class ErrorHandler
{

    /*
     * This function is a 404 error function. If the route or a view does
     * not exists it will throw an error. First it will check if you have
     * a custom 404 error page, if you don't have it, it will throw the
     * default error page. Please check for more examples in the /docs/errorpages.md
    */
    public static function httpNotFound() {
        if(file_exists('source/views/errors/404.php')) {
            require_once 'source/views/errors/404.php';
        } else {
            require_once 'SimpleHtmlWork/errors/404.php';
        }

    }

    /*
     * This function is a lang error function. If the language file does
     * not exists it will throw an error. First it will check if you have
     * a custom lang error page, if you don't have it, it will throw the
     * default error page. Please check for more examples in the /docs/errorpages.md
    */
    public static function languageFileNotFound() {
        if(file_exists('source/views/errors/lang.php')) {
            require_once 'source/views/errors/lang.php';
        } else {
            require_once 'SimpleHtmlWork/errors/lang.php';
        }

    }
}
