<?php
/*
 * Copyright (c) 2020 SimpleHtmlWork
 * https://github.com/Julianvschijndel/SimpleHtmlWork
 * --------------------------------------------------
 * SimpleHtmlWork. ~ Version: 1
 * --------------------------------------------
 *
 * Please do not edit this file if you don't know what you are doing.
 * I will not give support if you edit this file and SimpleHtmlWork is not
 * working anymore. If you know what you're doing and then you think
 * you can or actually can improve my code then please make a pull request
 * and I will look into it.
 *
*/

class Router
{
    /*
     * This is a private function for the routes. The function createRoutes will
     * store all the correct routes inside here. I highly recommend to not change
     * this code if you don't have any experience with PHP.
    */
    private $routes = [];

    /*
     * With this function you can create a route. I highly recommend to
     * not change this code if you don't have any experience with PHP.
    */
    function set($route, callable $closure) {
        $this->routes[$route] = $closure;
    }

    /*
     * This function will create the routes. First it will push everything inside
     * the private $routes variable that is located above then it will do a check
     * if the route a user is requested does exists in the $routes, if it does not
     * it will throw a 404 error page. I highly recommend to not change this code if
     * you don't have any experience with PHP.
    */
    function createRoutes() {
        $path = $_SERVER['REQUEST_URI'];
        if(array_key_exists($path, $this->routes)) {
            $this->routes[$path]();
        } else {
            ErrorHandler::httpNotFound();
        }
    }
}
