<?php
/*
 * Copyright (c) 2020 SimpleHtmlWork
 * https://github.com/Julianvschijndel/SimpleHtmlWork
 * --------------------------------------------------
 * SimpleHtmlWork. ~ Version: 1
 * --------------------------------------------
 *
 * Please do not edit this file if you don't know what you are doing.
 * I will not give support if you edit this file and SimpleHtmlWork is not
 * working anymore. If you know what you're doing and then you think
 * you can or actually can improve my code then please make a pull request
 * and I will look into it.
 *
*/

class Sw
{
    /**
     * View
     *
     * @param string $viewName
     * @return void
     */
    public static function View($viewName) {
        if(file_exists('source/views/'.$viewName.'.php')) {
            require_once 'source/views/'.$viewName.'.php';
        } else {
            ErrorHandler::httpNotFound();
        }
    }

    /**
     * include
     *
     * @param $file
     * @return void
     */
    public static function include($file){
        if(file_exists('source/includes/'.$file.'.php')) {
            require_once 'source/includes/'.$file.'.php';
        } else {
            ErrorHandler::httpNotFound();
        }
    }

    /**
     * Title
     *
     * @param string $appName
     * @param string $separator
     * @param string $title
     * @return string
    */
    public static function title($appName, $separator, $title){
        return $appName.' '.$separator.' '.$title;
    }
}
