<?php
/*
 * Copyright (c) 2020 SimpleHtmlWork
 * https://github.com/Julianvschijndel/SimpleHtmlWork
 * --------------------------------------------------
 * SimpleHtmlWork. ~ Version: 1
 * --------------------------------------------
 *
 * Please do not edit this file if you don't know what you are doing.
 * I will not give support if you edit this file and SimpleHtmlWork is not
 * working anymore. If you know what you're doing and then you think
 * you can or actually can improve my code then please make a pull request
 * and I will look into it.
 *
*/

class Sw
{
    /*
     * This function will return the view name a person has inserted.
     * So for example: Sw::view('index');
     * Please check for more examples in the /docs/view.md
    */
    public static function View($viewName) {
        if(file_exists('source/views/'.$viewName.'.php')) {
            require_once 'source/views/'.$viewName.'.php';
        } else {
            ErrorHandler::httpNotFound();
        }
    }

    /*
     * This function will create a title. You can set a name for the website, you can set a
     * separator like -- and the title of the website. You can call it like:
     * Sw::title('SimpleHtmlWork', '--', 'Welcome!');
     * Please check for more examples in the /docs/helpers.md
    */
    public static function title($appName, $separator, $title){
        return $appName.' '.$separator.' '.$title;
    }
}
