<?php
/*
 * Copyright (c) 2020 SimpleHtmlWork
 * https://github.com/Julianvschijndel/SimpleHtmlWork
 * --------------------------------------------------
 * SimpleHtmlWork. ~ Version: 1
 * --------------------------------------------
 *
 * Please do not edit this file if you don't know what you are doing.
 * I will not give support if you edit this file and SimpleHtmlWork is not
 * working anymore. If you know what you're doing and then you think
 * you can or actually can improve my code then please make a pull request
 * and I will look into it.
 *
*/

/*
 * Website configuration.
 * APP_NAME = is the name of you're application.
 * APP_URL = the url of you're application.
 * APP_CDN = the CDN of you're application, if you have this.
 * APP_LANG = the language of you're application.
 *
 * If you want to add custom config variables.
 * Please check how in the /docs/config.md
*/
define('APP_NAME', 'SimpleHtmlWork');
define('APP_URL', 'http://simplehtmlwork.loc/');
define('APP_CDN', 'https://cdn.juliandev.nl/');
define('APP_LANG', 'en');
