<?php
/*
 * Copyright (c) 2020 SimpleHtmlWork
 * https://github.com/Julianvschijndel/SimpleHtmlWork
 * --------------------------------------------------
 * SimpleHtmlWork. ~ Version: 1
 * --------------------------------------------
 *
 * Please do not edit this file if you don't know what you are doing.
 * I will not give support if you edit this file and SimpleHtmlWork is not
 * working anymore. If you know what you're doing and then you think
 * you can or actually can improve my code then please make a pull request
 * and I will look into it.
 *
*/

/*
 * Now we will create a function that will load everything.
 * All the classes, helpers, configuration files.
*/

// Autoload all the classes.
function classAutoLoad($fileName) {
    if(file_exists('SimpleHtmlWork/classes/'.$fileName.'.php')) {
        require_once 'SimpleHtmlWork/classes/'.$fileName.'.php';
    }
}
// Autoload all the helpers.
function helperAutoLoad($fileName) {
    if(file_exists('SimpleHtmlWork/helpers/'.$fileName.'.php')) {
        require_once 'SimpleHtmlWork/helpers/'.$fileName.'.php';
    }
}
// Autoload all the configuration files.
function configAutoLoad() {
    $files = glob('config/*.php', GLOB_BRACE);
    foreach($files as $file) {
        include ''.$file.'';
    }
}

// Register the autoloader(s).
spl_autoload_register('classAutoLoad');
spl_autoload_register('helperAutoLoad');

// Load all the configuration(s) files.
configAutoLoad();
