<?php
/*
 * Copyright (c) 2020 SimpleHtmlWork
 * https://github.com/Julianvschijndel/SimpleHtmlWork
 * --------------------------------------------------
 * SimpleHtmlWork. ~ Version: 1
 * --------------------------------------------
 *
 * Please do not edit this file if you don't know what you are doing.
 * I will not give support if you edit this file and SimpleHtmlWork is not
 * working anymore. If you know what you're doing and then you think
 * you can or actually can improve my code then please make a pull request
 * and I will look into it.
 *
*/

class Config
{
    /**
     * callback
     *
     * @param string $replace
     * @return string
    */
    private static function callback($replace) {

        $str = array(
            'name' => APP_NAME,
            'lang' => APP_LANG,
            'url' => APP_URL,
            'cdn' => APP_CDN,
        );

        foreach($str as $key => $value)
        {
            $replace = str_ireplace($key, $value, $replace);
        }
        return $replace;
    }

    /**
     * get
     *
     * @param $value
     * @return string
     */
    public static function get($value) {
        return self::callback($value);
    }
}
