<?php
/*
 * Copyright (c) 2020 SimpleHtmlWork
 * https://github.com/Julianvschijndel/SimpleHtmlWork
 * --------------------------------------------------
 * SimpleHtmlWork. ~ Version: 1
 * --------------------------------------------
 *
 * Please do not edit this file if you don't know what you are doing.
 * I will not give support if you edit this file and SimpleHtmlWork is not
 * working anymore. If you know what you're doing and then you think
 * you can or actually can improve my code then please make a pull request
 * and I will look into it.
 *
*/

class Config
{
    /*
     * With this function you can set values from the config file.
     * If you want to add custom config values:
     * Please check for more examples in the /docs/config.md
    */
    private static function callback($replace) {

        $str = array(
            'name' => APP_NAME,
            'lang' => APP_LANG,
            'url' => APP_URL,
            'cdn' => APP_CDN,
        );

        foreach($str as $key => $value)
        {
            $replace = str_ireplace($key, $value, $replace);
        }
        return $replace;
    }

    /*
     * With this function you can get a value of a config variable.
     * So for example you want to display the application name somewhere
     * inside your website you can simple do: Config::get('name')
    */
    public static function get($value) {
        return self::callback($value);
    }
}
